services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: mukki_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
